### ISSUE TITLE
web reader tests with remote URLs, EPUB (zipped vs. exploded),  RWPM manifest.json, GitHub vs. GitHack CDNs

### ISSUE THREAD

**Issue by danielweck** [edrlab/publications#2]
### Colibrio:
https://github.com/edrlab/publications/issues/2#issuecomment-2113186448
### Readium1:
https://github.com/edrlab/publications/issues/2#issuecomment-2113187457
### NYPL:
https://github.com/edrlab/publications/issues/2#issuecomment-2113188400
### DITA R2D2BC:
https://github.com/edrlab/publications/issues/2#issuecomment-2113189170
### VivlioStyle:
https://github.com/edrlab/publications/issues/2#issuecomment-2113189619
### Readium Playground / Thorium Web:
https://github.com/edrlab/publications/issues/2#issuecomment-2113307633

____________________________________________________________________
____________________________________________________________________

# exploded EPUB (raw HTML)

* GitHub SRC: https://github.com/edrlab/publications/blob/main/thorium3-documentation/sources/en/EPUB/pages/toc.xhtml
* GitHub CDN: https://raw.githubusercontent.com/edrlab/publications/main/thorium3-documentation/sources/en/EPUB/pages/toc.xhtml ( redirect from https://github.com/edrlab/publications/raw/main/thorium3-documentation/sources/en/EPUB/pages/toc.xhtml )
* GitHack DEV: https://raw.githack.com/edrlab/publications/main/thorium3-documentation/sources/en/EPUB/pages/toc.xhtml
* GitHack PROD: https://rawcdn.githack.com/edrlab/publications/main/thorium3-documentation/sources/en/EPUB/pages/toc.xhtml

Suggestion: using JavaScript, test presence of `navigator.epubReadingSystem` to trigger injection of TOC link at the top of all XHTML pages (so that exploded EPUB can be browsed online without EPUB reader)

____________________________________________________________________

# zipped EPUB

* GitHub SRC: https://github.com/edrlab/publications/blob/main/thorium3-documentation/sources/en.epub
* GitHub CDN: https://raw.githubusercontent.com/edrlab/publications/main/thorium3-documentation/sources/en.epub ( redirect from https://github.com/edrlab/publications/raw/main/thorium3-documentation/sources/en.epub )
* GitHack DEV: https://raw.githack.com/edrlab/publications/main/thorium3-documentation/sources/en.epub
* GitHack PROD: https://rawcdn.githack.com/edrlab/publications/main/thorium3-documentation/sources/en.epub

____________________________________________________________________

# RWPM

( https://github.com/readium/r2-streamer-js )

From GitHack DEV: https://raw.githack.com/edrlab/publications/main/thorium3-documentation/sources/en.epub

* Visual browsing: https://streamer.edrlab.org/pub/aHR0cHM6Ly9yYXcuZ2l0aGFjay5jb20vZWRybGFiL3B1YmxpY2F0aW9ucy9tYWluL3Rob3JpdW0zLWRvY3VtZW50YXRpb24vc291cmNlcy9lbi5lcHVi/manifest.json/show/all
* manifest JSON: https://streamer.edrlab.org/pub/aHR0cHM6Ly9yYXcuZ2l0aGFjay5jb20vZWRybGFiL3B1YmxpY2F0aW9ucy9tYWluL3Rob3JpdW0zLWRvY3VtZW50YXRpb24vc291cmNlcy9lbi5lcHVi/manifest.json

____________________________________________________________________

**Comment by danielweck** [comment]
____________________________________________________________________

# Colibrio

## exploded EPUB

(root dir)

- [x] GitHub CDN: https://demo.colibrio.com/?publication_url=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/
- [ ] GitHack DEV: https://demo.colibrio.com/?publication_url=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/
- [ ] GitHack PROD: https://demo.colibrio.com/?publication_url=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/

## exploded EPUB

(`META-INF/container.xml`)

- [ ] GitHub CDN: https://demo.colibrio.com/?publication_url=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml
- [ ] GitHack DEV: https://demo.colibrio.com/?publication_url=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml
- [ ] GitHack PROD: https://demo.colibrio.com/?publication_url=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml

## exploded EPUB

(`EPUB/package.opf`)

- [ ] GitHub CDN: https://demo.colibrio.com/?publication_url=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf
- [ ] GitHack DEV: https://demo.colibrio.com/?publication_url=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf
- [ ] GitHack PROD: https://demo.colibrio.com/?publication_url=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf

## zipped EPUB

- [x] GitHub CDN: https://demo.colibrio.com/?publication_url=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub ( redirect from https://github.com/edrlab/publications/raw/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub )
- [x] GitHack DEV: https://demo.colibrio.com/?publication_url=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub
- [x] GitHack PROD: https://demo.colibrio.com/?publication_url=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub

## RWPM (manifest JSON)

( https://raw.githack.com/edrlab/publications/main/thorium3-documentation/sources/en.epub )

- [ ] https://demo.colibrio.com/?publication_url=https://streamer.edrlab.org/pub/aHR0cHM6Ly9yYXcuZ2l0aGFjay5jb20vZWRybGFiL3B1YmxpY2F0aW9ucy9tYWluL3Rob3JpdW0zLWRvY3VtZW50YXRpb24vc291cmNlcy9lbi5lcHVi/manifest.json

____________________________________________________________________

**Comment by danielweck** [comment]
____________________________________________________________________

# Readium1

## exploded EPUB

(root dir)

- [x] GitHub CDN: https://readium.firebaseapp.com/?epub=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/
- [x] GitHack DEV: https://readium.firebaseapp.com/?epub=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/
- [x] GitHack PROD: https://readium.firebaseapp.com/?epub=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/

## exploded EPUB

(`META-INF/container.xml`)

- [ ] GitHub CDN: https://readium.firebaseapp.com/?epub=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml
- [ ] GitHack DEV: https://readium.firebaseapp.com/?epub=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml
- [ ] GitHack PROD: https://readium.firebaseapp.com/?epub=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml

## exploded EPUB

(`EPUB/package.opf`)

- [ ] GitHub CDN: https://readium.firebaseapp.com/?epub=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf
- [ ] GitHack DEV: https://readium.firebaseapp.com/?epub=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf
- [ ] GitHack PROD: https://readium.firebaseapp.com/?epub=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf

## zipped EPUB

- [x] GitHub CDN: https://readium.firebaseapp.com/?epub=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub ( redirect from https://github.com/edrlab/publications/raw/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub )
- [x] GitHack DEV: https://readium.firebaseapp.com/?epub=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub
- [x] GitHack PROD: https://readium.firebaseapp.com/?epub=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub

## RWPM (manifest JSON)

( https://raw.githack.com/edrlab/publications/main/thorium3-documentation/sources/en.epub )

- [ ] https://readium.firebaseapp.com/?epub=https://streamer.edrlab.org/pub/aHR0cHM6Ly9yYXcuZ2l0aGFjay5jb20vZWRybGFiL3B1YmxpY2F0aW9ucy9tYWluL3Rob3JpdW0zLWRvY3VtZW50YXRpb24vc291cmNlcy9lbi5lcHVi/manifest.json

____________________________________________________________________

**Comment by danielweck** [comment]
____________________________________________________________________

# NYPL

( https://github.com/NYPL-Simplified/web-reader )

## exploded EPUB

(root dir)

- [ ] GitHub CDN: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Fraw.githubusercontent.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen%2F
- [ ] GitHack DEV: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Fraw.githack.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen%2F
- [ ] GitHack PROD: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Frawcdn.githack.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen%2F

## exploded EPUB

(`META-INF/container.xml`)

- [ ] GitHub CDN: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Fraw.githubusercontent.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen%2FMETA-INF%2Fcontainer.xml
- [ ] GitHack DEV: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Fraw.githack.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen%2FMETA-INF%2Fcontainer.xml
- [ ] GitHack PROD: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Frawcdn.githack.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen%2FMETA-INF%2Fcontainer.xml

## exploded EPUB

(`EPUB/package.opf`)

- [ ] GitHub CDN: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Fraw.githubusercontent.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen%2FEPUB%2Fpackage.opf
- [ ] GitHack DEV: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Fraw.githack.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen%2FEPUB%2Fpackage.opf
- [ ] GitHack PROD: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Frawcdn.githack.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen%2FEPUB%2Fpackage.opf

## zipped EPUB

- [ ] GitHub CDN: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Fraw.githubusercontent.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen.epub ( redirect from https:%2F%2Fgithub.com%2Fedrlab%2Fpublications%2Fraw%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen.epub )
- [ ] GitHack DEV: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Fraw.githack.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen.epub
- [ ] GitHack PROD: https://nypl-web-reader.vercel.app/html/url/https:%2F%2Frawcdn.githack.com%2Fedrlab%2Fpublications%2F31b339f68b0c800bef5e85c2624115a49821483b%2Fthorium3-documentation%2Fsources%2Fen.epub

## RWPM (manifest JSON)

( https://raw.githack.com/edrlab/publications/main/thorium3-documentation/sources/en.epub )

- [x] https://nypl-web-reader.vercel.app/html/url/https:%2F%2Fstreamer.edrlab.org%2Fpub%2FaHR0cHM6Ly9yYXcuZ2l0aGFjay5jb20vZWRybGFiL3B1YmxpY2F0aW9ucy9tYWluL3Rob3JpdW0zLWRvY3VtZW50YXRpb24vc291cmNlcy9lbi5lcHVi%2Fmanifest.json

____________________________________________________________________

**Comment by danielweck** [comment]
____________________________________________________________________

# DITA R2D2BC reader

( https://github.com/d-i-t-a/R2D2BC )

## exploded EPUB

(root dir)

- [ ] GitHub CDN: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/
- [ ] GitHack DEV: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/
- [ ] GitHack PROD: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/

## exploded EPUB

(`META-INF/container.xml`)

- [ ] GitHub CDN: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml
- [ ] GitHack DEV: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml
- [ ] GitHack PROD: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml

## exploded EPUB

(`EPUB/package.opf`)

- [ ] GitHub CDN: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf
- [ ] GitHack DEV: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf
- [ ] GitHack PROD: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf

## zipped EPUB

- [ ] GitHub CDN: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub ( redirect from https://github.com/edrlab/publications/raw/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub )
- [ ] GitHack DEV: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub
- [ ] GitHack PROD: https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub

## RWPM (manifest JSON)

( https://raw.githack.com/edrlab/publications/main/thorium3-documentation/sources/en.epub )

- [x] https://rawcdn.githack.com/danielweck/R2D2BC/7664af31ece2e99aaa34aec6923fd80474f0986a/viewer/index_dita.html?url=https://streamer.edrlab.org/pub/aHR0cHM6Ly9yYXcuZ2l0aGFjay5jb20vZWRybGFiL3B1YmxpY2F0aW9ucy9tYWluL3Rob3JpdW0zLWRvY3VtZW50YXRpb24vc291cmNlcy9lbi5lcHVi/manifest.json

____________________________________________________________________

**Comment by danielweck** [comment]
____________________________________________________________________

# Vivliostyle

( https://github.com/vivliostyle/vivliostyle.js )

## exploded EPUB

(root dir)

- [x] GitHub CDN: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/
- [ ] GitHack DEV: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/
- [ ] GitHack PROD: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/

## exploded EPUB

(`META-INF/container.xml`)

- [ ] GitHub CDN: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml
- [ ] GitHack DEV: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml
- [ ] GitHack PROD: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml

## exploded EPUB

(`EPUB/package.opf`)

- [x] GitHub CDN: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf
- [x] GitHack DEV: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf
- [x] GitHack PROD: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf

## zipped EPUB

- [ ] GitHub CDN: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub ( redirect from https://github.com/edrlab/publications/raw/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub )
- [ ] GitHack DEV: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub
- [ ] GitHack PROD: https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub

## RWPM (manifest JSON)

( https://raw.githack.com/edrlab/publications/main/thorium3-documentation/sources/en.epub )

- [x] https://vivliostyle.github.io/vivliostyle.js/viewer/vivliostyle-viewer.html#b=https://streamer.edrlab.org/pub/aHR0cHM6Ly9yYXcuZ2l0aGFjay5jb20vZWRybGFiL3B1YmxpY2F0aW9ucy9tYWluL3Rob3JpdW0zLWRvY3VtZW50YXRpb24vc291cmNlcy9lbi5lcHVi/manifest.json

____________________________________________________________________

**Comment by danielweck** [comment]
____________________________________________________________________

# Readium Playground / Thorium Web

( https://github.com/readium/playground ==> https://github.com/edrlab/thorium-web )

## exploded EPUB

(root dir)

- [ ] GitHub CDN: https://playground.readium.org/read?book=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/
- [ ] GitHack DEV: https://playground.readium.org/read?book=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/
- [ ] GitHack PROD: https://playground.readium.org/read?book=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/

## exploded EPUB

(`META-INF/container.xml`)

- [ ] GitHub CDN: https://playground.readium.org/read?book=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml
- [ ] GitHack DEV: https://playground.readium.org/read?book=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml
- [ ] GitHack PROD: https://playground.readium.org/read?book=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/META-INF/container.xml

## exploded EPUB

(`EPUB/package.opf`)

- [ ] GitHub CDN: https://playground.readium.org/read?book=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf
- [ ] GitHack DEV: https://playground.readium.org/read?book=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf
- [ ] GitHack PROD: https://playground.readium.org/read?book=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en/EPUB/package.opf

## zipped EPUB

- [ ] GitHub CDN: https://playground.readium.org/read?book=https://raw.githubusercontent.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub ( redirect from https://github.com/edrlab/publications/raw/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub )
- [ ] GitHack DEV: https://playground.readium.org/read?book=https://raw.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub
- [ ] GitHack PROD: https://playground.readium.org/read?book=https://rawcdn.githack.com/edrlab/publications/31b339f68b0c800bef5e85c2624115a49821483b/thorium3-documentation/sources/en.epub

## RWPM (manifest JSON)

( https://raw.githack.com/edrlab/publications/main/thorium3-documentation/sources/en.epub )

- [ ] https://playground.readium.org/read?book=https://streamer.edrlab.org/pub/aHR0cHM6Ly9yYXcuZ2l0aGFjay5jb20vZWRybGFiL3B1YmxpY2F0aW9ucy9tYWluL3Rob3JpdW0zLWRvY3VtZW50YXRpb24vc291cmNlcy9lbi5lcHVi/manifest.json

( https://publication-server.readium.org/bW9ieS1kaWNrLmVwdWI/manifest.json )

- [x] https://playground.readium.org/read?book=https%3A%2F%2Fpublication-server.readium.org%2FbW9ieS1kaWNrLmVwdWI

( https://publication-server.readium.org/QmVsbGFPcmlnaW5hbDMuZXB1Yg/manifest.json )

- [x] https://playground.readium.org/read?book=https%3A%2F%2Fpublication-server.readium.org%2FQmVsbGFPcmlnaW5hbDMuZXB1Yg

____________________________________________________________________

**Comment by gautierchomel** [comment]
New valid address : https://streamer.edrlab.org/readerNYPL/?url=https%3A%2F%2Fstreamer.edrlab.org%2Fpub%2FaHR0cHM6Ly9naXRodWIuY29tL2VkcmxhYi9wdWJsaWNhdGlvbnMvcmF3L21haW4vdGhvcml1bTMtZG9jdW1lbnRhdGlvbi9zb3VyY2VzL2VuLmVwdWI%3D%2Fmanifest.json

**Comment by danielweck** [comment]
To track: https://github.com/readium/playground/issues/36

**Comment by gautierchomel** [comment]
Closing as tracking will follow up from https://github.com/readium/playground/issues/36 (and the doc as epub now stands at the https://github.com/edrlab/thorium-reader-doc repo)
